name: Deploy .NET Core Backend to Azure

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'whateverAPI/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: whateverbruh
  AZURE_WEBAPP_PACKAGE_PATH: './whateverAPI'
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set up Node.js (for any build tools)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Build application
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Publish application
      run: dotnet publish -c Release -o ./publish --no-build
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish 